import mongoose from "mongoose";

/**
 * InterviewSession Model
 * Core document that tracks a single interview attempt.
 * Frontend pages that use this:
 *   - InterviewSetup  → creates the session (job role, tech stack, difficulty)
 *   - AIInterviewRoom → reads questions[], records answers[]
 *   - LiveInterviewRoom → socket events update this session
 *   - Reports         → reads session for context
 */

// A single question-answer pair within a session
const questionAnswerSchema = new mongoose.Schema(
  {
    question: { type: String, required: true },
    answer: { type: String, default: "" },
    aiFeedback: { type: String, default: "" }, // Per-answer AI feedback
    score: { type: Number, default: null }, // 0–10 score for this answer
    answeredAt: { type: Date, default: null },
  },
  { _id: false }, // No separate _id for sub-documents
);

const interviewSessionSchema = new mongoose.Schema(
  {
    // Who is being interviewed
    candidate: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // Who is conducting (null for AI sessions)
    interviewer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    // Interview configuration (set during InterviewSetup page)
    jobRole: {
      type: String,
      required: [true, "Job role is required"],
      trim: true,
    },

    techStack: {
      type: [String], // e.g. ["React", "Node.js", "MongoDB"]
      default: [],
    },

    difficulty: {
      type: String,
      enum: ["beginner", "intermediate", "advanced"],
      default: "intermediate",
    },

    type: {
      type: String,
      enum: ["ai", "live"], // AIInterviewRoom vs LiveInterviewRoom
      default: "ai",
    },

    // Questions generated by AI and candidate answers
    questionsAndAnswers: {
      type: [questionAnswerSchema],
      default: [],
    },

    // Session lifecycle
    status: {
      type: String,
      enum: ["pending", "active", "completed", "cancelled"],
      default: "pending",
    },

    // For live interviews — links to a Room
    roomId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Room",
      default: null,
    },

    scheduledAt: {
      type: Date,
      default: null,
    },

    startedAt: {
      type: Date,
      default: null,
    },

    completedAt: {
      type: Date,
      default: null,
    },

    // Duration in minutes
    duration: {
      type: Number,
      default: 30,
    },
  },
  {
    timestamps: true,
  },
);

const InterviewSession = mongoose.model(
  "InterviewSession",
  interviewSessionSchema,
);
export default InterviewSession;
